


# Numpy array slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [1]:
# slicing ele from index 1 to index 5
import  numpy as np

arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])  # starts with 2 and ends before 6

[2 3 4 5]


In [2]:
# slice elements from index 4 to end
print(arr[4:])

[5 6 7]


In [3]:
# slicing from begining to index 4

print(arr[:4])


[1 2 3 4]


# Negative slicing

In [4]:
# slice from index 3 from end to index 1 from the end
print(arr[-3:-1])

[5 6]


Use the step value to determine the step of the slicing:


In [5]:
# returing every other elemnt from 1 to index 5
print(arr[1:5:2])

[2 4]


# SLicing 2-D array,

In [2]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [7]:
# from both element return ele of index 2

print(arr[0:2,2])

[3 8]


In [8]:
# from both elements slicing  dfferently
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [2]:
import numpy as np

# Step 1: Create the 2D array
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# Step 2: Perform indexing operations
element = arr[1, 2]   # 2nd row, 3rd column (Indexing starts from 0)
first_row = arr[0, :] # Extract first row
second_col = arr[:, 1] # Extract second column
submatrix = arr[1:, 1:] # Extract bottom-right 2x2 matrix

# Step 3: Print results
print("Element at (2,3):", element)
print("First row:", first_row)
print("Second column:", second_col)
print("Bottom-right 2x2 submatrix:\n", submatrix)


Element at (2,3): 6
First row: [1 2 3]
Second column: [2 5 8]
Bottom-right 2x2 submatrix:
 [[5 6]
 [8 9]]


In [1]:
import numpy as np

# Step 1: Create the 3×4 array
arr = np.array([[10, 20, 30, 40], 
                [50, 60, 70, 80], 
                [90, 100, 110, 120]])

# Step 2: Perform indexing & slicing
element = arr[1, 2]   # 2nd row, 3rd column (Indexing starts from 0)
first_row = arr[0, :] # Extract first row
third_col = arr[:, 2] # Extract third column
submatrix = arr[1:, 2:] # Extract bottom-right 2x2 submatrix
slice_part = arr[:2, :3] # Extract first two rows and first three columns

# Step 3: Print results
print("Element at (2,3):", element)
print("First row:", first_row)
print("Third column:", third_col)
print("Bottom-right 2x2 submatrix:\n", submatrix)
print("First two rows & first three columns:\n", slice_part)


Element at (2,3): 70
First row: [10 20 30 40]
Third column: [ 30  70 110]
Bottom-right 2x2 submatrix:
 [[ 70  80]
 [110 120]]
First two rows & first three columns:
 [[10 20 30]
 [50 60 70]]
