
# Numpy Data Types

In [1]:
# data type of an array
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [3]:
# data type of an array containing strings
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) 
# <U6 means unicode with each element contains max 6 chars

<U6


In [4]:
# creating arrays with defined data type

arr = np.array([1,2,4,5],dtype='S') #converts to string and stored in byte string 
print(arr)
print(arr.dtype)  #op s1 --> each element is string and it is in 1 byte


[b'1' b'2' b'4' b'5']
|S1


In [2]:
arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)   #4 byte int

[1 2 3 4]
int32


# Converting Data Type on Existing Arrays

In [6]:

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')# make a copy of array  and specify the data type 

# float to int using i --> int32
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)
# float to int using int  --> int64

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [9]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
